# Multi-Depot Vehicle Routing Problem with Time Windows and Heterogeneous Fleet
# Problem Definition and Instance Generation
# Author: AI Assistant

library(dplyr)

#' Generate a random problem instance for MDVRPTWH
#' 
#' @param num_depots Number of depots (default: 2)
#' @param num_customers Number of customers (default: 7)
#' @param num_vehicles Number of vehicles (default: 2)
#' @param num_vehicle_types Number of different vehicle types (default: 2)
#' @param grid_size Size of the coordinate grid (default: 100)
#' @param seed Random seed for reproducibility (default: 42)
#' 
#' @return A list containing the problem instance with depots, customers, vehicles, and distance matrix
#' @export
generate_problem_instance <- function(num_depots = 2, 
                                     num_customers = 7, 
                                     num_vehicles = 2, 
                                     num_vehicle_types = 2,
                                     grid_size = 100,
                                     seed = 42) {
  set.seed(seed)
  
  # Generate depot coordinates and properties
  depots <- data.frame(
    depot_id = 1:num_depots,
    x = runif(num_depots, 0, grid_size),
    y = runif(num_depots, 0, grid_size),
    name = paste("Depot", 1:num_depots),
    capacity = rep(1000, num_depots),  # Large depot capacity
    open_time = rep(0, num_depots),    # Depots open at time 0
    close_time = rep(480, num_depots)  # Depots close at 8 hours (480 minutes)
  )
  
  # Generate customer coordinates and properties
  customers <- data.frame(
    customer_id = 1:num_customers,
    x = runif(num_customers, 0, grid_size),
    y = runif(num_customers, 0, grid_size),
    demand = sample(10:50, num_customers, replace = TRUE),
    service_time = sample(10:30, num_customers, replace = TRUE),
    early_time = pmax(0, sample(0:300, num_customers, replace = TRUE)),
    late_time = pmin(480, sample(200:480, num_customers, replace = TRUE)),
    name = paste("Customer", 1:num_customers)
  )
  
  # Ensure late_time > early_time
  customers$late_time <- pmax(customers$late_time, customers$early_time + customers$service_time)
  
  # Define vehicle types
  vehicle_types <- data.frame(
    type_id = 1:num_vehicle_types,
    type_name = c("Small Van", "Large Truck")[1:num_vehicle_types],
    capacity = c(100, 200)[1:num_vehicle_types],
    speed = c(1.0, 0.8)[1:num_vehicle_types],  # km/minute
    fixed_cost = c(50, 80)[1:num_vehicle_types],
    variable_cost = c(1.0, 1.5)[1:num_vehicle_types]  # cost per unit distance
  )
  
  # Generate vehicles
  vehicles <- data.frame(
    vehicle_id = 1:num_vehicles,
    depot_id = sample(1:num_depots, num_vehicles, replace = TRUE),
    type_id = sample(1:num_vehicle_types, num_vehicles, replace = TRUE)
  ) %>%
    left_join(vehicle_types, by = "type_id") %>%
    left_join(depots[, c("depot_id", "x", "y")], by = "depot_id", suffix = c("", "_depot"))
  
  # Calculate distance matrix (Euclidean distance)
  all_locations <- rbind(
    depots[, c("x", "y")] %>% mutate(type = "depot", id = depots$depot_id),
    customers[, c("x", "y")] %>% mutate(type = "customer", id = customers$customer_id)
  )
  
  n_locations <- nrow(all_locations)
  distance_matrix <- matrix(0, n_locations, n_locations)
  
  for (i in 1:n_locations) {
    for (j in 1:n_locations) {
      if (i != j) {
        distance_matrix[i, j] <- sqrt((all_locations$x[i] - all_locations$x[j])^2 + 
                                     (all_locations$y[i] - all_locations$y[j])^2)
      }
    }
  }
  
  # Create time matrix based on distance and vehicle speed
  # For simplicity, use average vehicle speed
  avg_speed <- mean(vehicle_types$speed)
  time_matrix <- distance_matrix / avg_speed
  
  problem <- list(
    depots = depots,
    customers = customers,
    vehicles = vehicles,
    vehicle_types = vehicle_types,
    distance_matrix = distance_matrix,
    time_matrix = time_matrix,
    all_locations = all_locations,
    parameters = list(
      num_depots = num_depots,
      num_customers = num_customers,
      num_vehicles = num_vehicles,
      num_vehicle_types = num_vehicle_types,
      grid_size = grid_size,
      seed = seed
    )
  )
  
  return(problem)
}

#' Generate a summary of the problem instance
#' 
#' @param problem A problem instance generated by generate_problem_instance
#' 
#' @return A character string with problem summary
#' @export
generate_problem_summary <- function(problem) {
  if (is.null(problem)) {
    return("No problem instance available.")
  }
  
  total_demand <- sum(problem$customers$demand)
  total_capacity <- sum(problem$vehicles$capacity)
  
  summary_text <- paste(
    "MDVRPTWH Problem Instance Summary:",
    paste("- Depots:", nrow(problem$depots)),
    paste("- Customers:", nrow(problem$customers)),
    paste("- Vehicles:", nrow(problem$vehicles)),
    paste("- Vehicle Types:", nrow(problem$vehicle_types)),
    paste("- Total Customer Demand:", total_demand),
    paste("- Total Vehicle Capacity:", total_capacity),
    paste("- Capacity Utilization:", round(total_demand / total_capacity * 100, 1), "%"),
    "",
    "Vehicle Distribution:",
    paste(capture.output(print(table(problem$vehicles$type_name))), collapse = "\n"),
    "",
    "Time Windows:",
    paste("- Earliest service time:", min(problem$customers$early_time)),
    paste("- Latest service time:", max(problem$customers$late_time)),
    sep = "\n"
  )
  
  return(summary_text)
}

#' Validate a problem instance
#' 
#' @param problem A problem instance to validate
#' 
#' @return A list with validation results
#' @export
validate_problem_instance <- function(problem) {
  errors <- c()
  warnings <- c()
  
  # Check if all required components exist
  required_components <- c("depots", "customers", "vehicles", "vehicle_types", 
                          "distance_matrix", "time_matrix")
  
  for (component in required_components) {
    if (!component %in% names(problem)) {
      errors <- c(errors, paste("Missing component:", component))
    }
  }
  
  if (length(errors) > 0) {
    return(list(valid = FALSE, errors = errors, warnings = warnings))
  }
  
  # Check depot data
  if (nrow(problem$depots) == 0) {
    errors <- c(errors, "No depots defined")
  }
  
  # Check customer data
  if (nrow(problem$customers) == 0) {
    errors <- c(errors, "No customers defined")
  }
  
  # Check vehicles
  if (nrow(problem$vehicles) == 0) {
    errors <- c(errors, "No vehicles defined")
  }
  
  # Check time windows consistency
  invalid_windows <- problem$customers$late_time <= problem$customers$early_time
  if (any(invalid_windows)) {
    errors <- c(errors, paste("Invalid time windows for customers:", 
                             paste(which(invalid_windows), collapse = ", ")))
  }
  
  # Check capacity vs demand
  total_demand <- sum(problem$customers$demand)
  total_capacity <- sum(problem$vehicles$capacity)
  
  if (total_demand > total_capacity) {
    warnings <- c(warnings, "Total demand exceeds total vehicle capacity")
  }
  
  # Check distance matrix dimensions
  expected_size <- nrow(problem$depots) + nrow(problem$customers)
  if (nrow(problem$distance_matrix) != expected_size || 
      ncol(problem$distance_matrix) != expected_size) {
    errors <- c(errors, "Distance matrix dimensions do not match number of locations")
  }
  
  return(list(
    valid = length(errors) == 0,
    errors = errors,
    warnings = warnings
  ))
}